### ISSUE TITLE
Guide/documentation about integration to DefectDojo

### ISSUE THREAD

**Issue by elle024** [SPoint42/SecurityTools#1]
Hello,

Good day!

I am trying to integrate and install your tool from our codebase. We are currently using Security Code scan to perform security on our code and we would like to integrate the report to DefectDojo using your tool. However, there are no documentation or guidelines on how to do this. Can I ask for a link or a wiki on how to do this? I am new in using python and don't know much about it so it is challenge to me to perform this task without additional documentation.

Thank you so much

**Comment by SPoint42** [comment]
Hi,

I suggest to use now SARIf import who is really stable on Defectdojo
